### ISSUE TITLE
Application stuck at "Mounting partition 0x800"

### ISSUE THREAD

**Issue by Voxel9** [tomtomdu80/VitaRW#1]
Hello,

It seems I am having trouble when I try to run the app after I built it.
As the title states, the app keeps getting constantly stuck at "Mounting partition 0x800 with RW permissions..." and doesn't seem to go any further, even when I retry the app another ~5 times.

Additionally, I would like to point out that I am building with the latest SDK, and built VitaRW with the full version of libSceVshBridge (the one that is ~160kb in size). Should I do something with the 'extra' folder that contains the extra.json and the 2kb version of libSceVshBridge?

And finally, I encounter these warnings every time I try to build:
`arm-vita-eabi-gcc -Wl,-q -Wall -O3   -c -o main.o main.c
main.c: In function 'main':
main.c:33:3: warning: implicit declaration of function 'vshIoUmount' [-Wimplicit-function-declaration]
   vshIoUmount(i * 0x100, 0, 0, 0); // id, unk1, unk2, unk3 (flags ?)
   ^
main.c:36:3: warning: implicit declaration of function '_vshIoMount' [-Wimplicit-function-declaration]
   _vshIoMount(i * 0x100, 0, 2, buf); // id, unk, permission, work_buffer
   ^`
Is this a normal thing to happen?

Apologies for opening an issue here, and thank you very much if you could help me out with building correctly.
-Voxel

**Comment by MajorTomSec** [comment]
It's supposed to get stuck on the id 0x800. Just press the PS button and go back in the homebrew, the app will get unstuck. I forgot to mention it in the readme, I will add it.

I didn't know the libSceVshBridge was added in the latest version on the SDK, so just don't bother with the extra directory.

I don't know the exact arguments of the functions so I didn't bother declaring the functions properly, that's why you get those warns.

**Comment by Voxel9** [comment]
Ah; it works now! Thanks for that. :+1:
