### ISSUE TITLE
[Q] Is there any permission list for _vshIoMount?

### ISSUE THREAD

**Issue by Yoti** [tomtomdu80/VitaRW#4]
I'm talking about third arg - permission. Which used for RO mode? Zero or one?

**Comment by MajorTomSec** [comment]
I can't remember testing all of the different values for the permission argument, although I know that 0 is read-only. It might not be the correct way to set the partition back to the original mode, as you may notice that, indeed, files are read-only again, but the vita still has a few problems dealing with a few partitions. For example, once you mount gro0 with permission 0, the vita will try installing the cartridge, but will eventually fail. I believe the permission 1 might be used instead, since, using this mode, the partitions are not writable either.
Mode 0 and 1 seem to be very similar, but permission 1 might be the correct one to use if you want to re-mount the partitions as read-only. I have not tested the permission 1 myself, as I don't have the time right now, I can try it out this WE probably, unless someone else does before.

**Comment by Yoti** [comment]
Ok, thanks. Clear for now.

**Comment by Cpasjuste** [comment]
Hi, i have a question too and i think it does not require a new "thread". So my question is it is possible to umount/remount the app0 device ?

**Comment by MajorTomSec** [comment]
App0 is a pure virtual mountpoint, described as an overlay in libfios2. This is not directly mounted from a physical partition. 
AFAIK, however, app0 is writable using libfios2 directly

**Comment by Cpasjuste** [comment]
Who, would be cool for the app i'm working on (debug shell). Do you have any examples or directions ?

**Comment by MajorTomSec** [comment]
Unfortunately I don't have any sample code ATM. I also never managed to use it myself as I wasn't able to correctly initialize the library back then, but should be trivial now. 
Just take a look at the fios2 user api module

**Comment by Cpasjuste** [comment]
Thanks for the tips :) 

When you say the fios2 user api module, you mean  : https://github.com/vitasdk/vita-headers/blob/1fc4480e7cba02c1daebd3d74715e97df4d7e95c/db.json#L987 ? I have yet to find the correct implementation/usage isn't it ?

**Comment by MajorTomSec** [comment]
Yes, that's it

**Comment by Cpasjuste** [comment]
So, i did succeed in using libFios2 (was hard :)), but it does not allow to write to app0 (it seems). I can write anywhere with it so the code is right. I can also overlay (remap) a dir to app0, but sceAppMgrLoadExec does not allow to launch anything (like app0:/eboot2.bin). I guess when it get executed my overlays are closed. 
Are you sure we can write directly to app0: with fios2 ? (it seems not: "insufficient privileges" error)

Else thanks, this was interesting :)

**Comment by SilicaAndPina** [comment]
@Cpasjuste please see main.c of my "trophaxSE" to see how to unmount app0: write new files and then mount app0 again . - .

**Comment by Cpasjuste** [comment]
Thanks mate but I did succeed in that maybe a year ago :p (see psp2shell)
